apiVersion: v1
kind: Service
metadata:
  name: odoo-postgres
  labels:
    app: odoo
spec:
  ports:
    - port: 5432
  selector:
    app: odoo
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: odoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-postgres
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: odoo
        tier: postgres
    spec:
      containers:
      - image: postgres:17.0
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: Gio123
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: giova
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim

